% demo_plot.m

drop=6633;

[p,t,th,s,d]=get_thetasd2_mmp(drop,'t_uf','','','');


% read v1 and low-pass
v1=atod1_mmp(read_rawdata_mmp('v1',drop));
[b,a]=cheby1(4,3,40/400);
v1_lp=filtfilt(b,a,v1);

% read pressure, offset and interpolate to match v1
pr=pr_offset1_mmp(drop,'v1',pr3_mmp(drop));
nv1=length(v1);
pr_v1=interp1((1:16:nv1),pr,(1:nv1));

% window v1 data
imax=find(pr_v1==max(pr_v1));
imax=imax-400;
imin=max(find(pr_v1<=.03));
v1_lp=v1_lp(imin:imax); pr_v1=pr_v1(imin:imax);

[epsilon, pr_eps]=get_epsilon1_mmp(drop);

% calculate plotting limits
maxv1=max(v1_lp); minv1=min(v1_lp); spanv1=maxv1-minv1;
maxv1=maxv1+.02*spanv1; minv1=minv1-.02*spanv1;
maxt=max(t); mint=min(t); spant=maxt-mint;
maxt=maxt+.02*spant; mint=mint-.02*spant;
maxp=max(p)-.01; minp=0;


clf
pos1=[.1 .1 .45 .7];
pos2=[.6 .1 .25 .7];

ax1=axes('position',pos1,'ydir','rev',...
   'xlim',[minv1 maxv1],...
   'ylim',[minp maxp],...
   'fontsize',12,...
   'ticklength',[.02 .02],...
   'linewidth',1,...
   'fontweight','bold');
Hv1=line(v1_lp,pr_v1);
xlabel('v1 / volts'), ylabel('p / MPa')


ax2=axes('position',get(ax1,'position'),...
   'ydir','rev',...
   'xlim',[mint maxt],...
   'xaxislocation','top',...
   'yaxislocation','right',...
   'yticklabel','',...
   'ylim',[minp maxp],...
   'ticklength',[.02 .02],...
   'xcolor','r',...
   'fontsize',12,...
   'linewidth',1,...
   'fontweight','bold');
Ht=line(t,p,'parent',ax2,'color','r');
xlabel('T / {}^o C')

ax3=axes('position',pos2,'ydir','rev',...
   'yticklabel','',...
   'ylim',[minp maxp]);
%semilogx(epsilon,pr_eps)
Hp=stair_plot(log10(epsilon),pr_eps,'y','y');
Heps=fillstair(log10(epsilon),pr_eps,'y',-10,[.7 .7 .7],'k');
set(ax3,'ydir','rev',...
   'yticklabel','',...
   'ylim',[minp maxp],...
   'xlim',[-10 -6],...
   'fontsize',12,...
   'linewidth',1,...
   'xtick',[-10:-6],...
   'ticklength',[.02 .02],...
   'fontweight','bold')
xlabel('log(\epsilon / W kg^{-1})')