% mmctl5.m

 Hc_label = uicontrol(gcf,'Style','text',...
        'Position',[10 10 70 20],...
        'String','Colormap:');

 Hc_map = uicontrol(gcf,'Style','edit',...
        'Position',[80 10 60 20],...
        'String','hsv',...
        'callback','colormap(eval(get(Hc_map,''String'')))');

 Hc_multi = uicontrol(gcf,'Style','edit',...
        'Position',[20 50 75 75],...
        'String','Line 1|Line 2|Line 3',...
        'Max',2);
