% mmctl3.m

Hc_box = uicontrol(gcf,'Style','check',...
          'Position',[100 50 100 20],...
          'String','Axis Box',...
          'CallBack',[...
              'if get(Hc_box,''Value'')==1,'...
                  'set(gca,''Box'',''on''),'...
              'else,'...
                  'set(gca,''Box'',''off''),'...
              'end']);
