% mmctl2.m

 Hc_boxon = uicontrol(gcf,'Style','radio',...
          'Position',[20 45 100 20],...
          'String','Set Box On',...
          'Value',0,...
          'CallBack',[...
              'set(Hc_boxon,''Value'',1),'...
              'set(Hc_boxoff,''Value'',0),'...
              'set(gca,''Box'',''on'')']);

 Hc_boxoff = uicontrol(gcf,'Style','radio',...
          'Position',[20 20 100 20],...
          'String','Set Box Off',...
          'Value',1,...
          'CallBack',[...
              'set(Hc_boxon,''Value'',0),'...
              'set(Hc_boxoff,''Value'',1),'...
              'set(gca,''Box'',''off'')']);
