% mmenu3.m

Hm_top = uimenu('Label','Example');
Hm_box = uimenu(Hm_top,'Label','Axis Box',...
           'CallBack',[...
              'if strcmp(get(gca,''Box''),''on''),',...
                 'set(gca,''Box'',''off''),',...
                 'set(Hm_box,''Label'',''Set Box On''),',...
              'else,',...
                 'set(gca,''Box'',''on''),',...
                 'set(Hm_box,''Label'',''Set Box Off''),',...
              'end']);
