% mmenu4.m

Hm_top = uimenu('Label','Example');
Hm_boxon = uimenu(Hm_top,'Label','Set Box On',...
              'CallBack',[...
                 'set(gca,''Box'',''on''),',...
                 'set(Hm_boxon,''Enable'',''off''),',...
                 'set(Hm_boxoff,''Enable'',''on'')']);
Hm_boxoff = uimenu(Hm_top,'Label','Set Box Off',...
              'Enable','off',...
              'CallBack',[...
                 'set(gca,''Box'',''off''),',...
                 'set(Hm_boxon,''Enable'',''on''),',...
                 'set(Hm_boxoff,''Enable'',''off'')']);
